// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

// export default defineConfig({
//   schema: 'prisma/schema.prisma',
//   migrations: {
//     path: 'prisma/migrations',
//     seed: 'tsx prisma/seed/seed.ts'
//   },
//   datasource: {
//     url: process.env['DATABASE_URL']
//   }
// })
export default defineConfig({
  schema: 'prisma/legacy/schema.prisma',
  migrations: {
    path: 'prisma/legacy/migrations',
    seed: 'tsx prisma/legacy/seed/seed.ts'
  },
  datasource: {
    url: process.env['LEGACY_DATABASE_URL']
  }
})
